
name: Weather Alert Updater

on:
  schedule:
    # Every 15 minutes on Saturdays (CFB)
    - cron: '*/15 * * * 6'
    # Every 15 minutes on Sundays (NFL)
    - cron: '*/15 * * * 0'
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run weather alert script
        run: python data/weather/update_weather_openweathermap.py
